### ISSUE TITLE
Cannot Import Google Module

### ISSUE THREAD

**Issue by iethan** [GoogleCloudPlatform/appengine-python-vm-runtime#123]
I started out thinking this was a user error when following these instructions: https://developers.google.com/api-client-library/python/auth/service-accounts. However, after working through the problem for a couple of days, realized this could be a larger implementation issue. 

The objective is to pull cell values from Sheets API into App Engine in the dev_appserver.py (for development) and gcloud app deploy environments. 

Issue is the dev_appserver.py environment cannot import modules but deployment works fine. 

I'm receiving the following error when executing the dev_appserver.py:

    from google.auth import app_engine
    File "/google/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/    python/runtime/sandbox.py"
    , line 1147, in load_module
        raise ImportError('No module named %s' % fullname)
    ImportError: No module named google.auth
Odd thing is when I deploy the app, it works fine. 

I tried (based off: https://stackoverflow.com/questions/18554364/google-app-engine-dev-appserver-py-problems):

1. dev_appserver.py MY_DIRECTORY
1. cd /google/google-cloud-sdk/bin/; python dev_appserver.py MY_DIRECTORY 
1. python  dev_appserver.py hello_world/
1. Installed updated gcloud components install app-engine-go

Additional info:

1. No virtual env is being used.
1. path to dev_appserver: /google/google-cloud-sdk/bin/dev_appserver.py
1. I'm using Google's Console Cloudshell
1. Here are the SDK versions:

- Google Cloud SDK 192.0.0
- alpha 2017.09.15
- app-engine-go
- app-engine-java 1.9.63
- app-engine-php " "
- app-engine-python 1.9.67
- app-engine-python-extras 1.9.63
- beta 2017.09.15
- bq 2.0.29
- cbt
- cloud-datastore-emulator 1.4.1
- core 2018.03.02
- datalab 20180213
- docker-credential-gcr
- gcd-emulator v1beta3-1.0.0
- gsutil 4.28
- kubectl
- pubsub-emulator 2018.02.02

Files:

app.yaml

    runtime: python27
    api_version: 1
    threadsafe: true
    
    handlers:
    - url: /.*
      script: main.app
    
    libraries:
    - name: flask
      version: 0.12
    - name: six
      version: "1.9.0" 

appengine_config.py

    from google.appengine.ext import vendor
    import os
    
    vendor.add(os.path.join(os.path.dirname(os.path.realpath(__file__)),'lib'))

main.py

    import logging
    
    from flask import Flask
    from sheets import data
    
    app = Flask(__name__)
    
    
    @app.route('/')
    def hello():
        return 'Hello World!{}'.format(data)
    
    
    @app.errorhandler(500)
    def server_error(e):
        # Log the error and stacktrace.
        logging.exception('An error occurred during a request.')
        return 'An internal error occurred.', 500

sheets.py

    from google.auth import app_engine
    import googleapiclient.discovery
    
    SCOPES = ['https://www.googleapis.com/auth/drive',
              'https://www.googleapis.com/auth/drive.file',
              'https://www.googleapis.com/auth/drive.readonly',
              'https://www.googleapis.com/auth/spreadsheets.readonly',
              'https://www.googleapis.com/auth/sqlservice.admin']
    
    spreadsheetId = '<spreadsheet-id>'
    rangeName = 'A1:A5'
    
    credentials = app_engine.Credentials(scopes=SCOPES)
    service = googleapiclient.discovery.build('sheets', 'v4', credentials=credentials)
    
    data = service.spreadsheets().values().get(spreadsheetId=spreadsheetId,     
    range=rangeName).execute()
    data = data.get('values',[])

/lib

    .
    ..
    apiclient
    cachetools
    cachetools-2.0.1.dist-info
    google
    googleapiclient
    google_api_python_client-1.5.2.dist-info
    google_api_python_client-1.6.5.dist-info
    google_auth-1.4.1.dist-info
    google_auth-1.4.1-py3.6-nspkg.pth
    google_auth_httplib2-0.0.3.dist-info
    google_auth_httplib2.py
    google_auth_httplib2.pyc
    httplib2
    httplib2-0.10.3.dist-info
    oauth2client
    oauth2client-2.2.0.dist-info
    oauth2client-4.1.2.dist-info
    pyasn1
    pyasn1-0.4.2.dist-info
    pyasn1_modules
    pyasn1_modules-0.2.1.dist-info
    rsa
    rsa-3.4.2.dist-info
    simplejson
    simplejson-3.13.2.dist-info
    six-1.11.0.dist-info
    six.py
    six.pyc
    uritemplate
    uritemplate-0.6.dist-info
    uritemplate-3.0.0.dist-info

Based on this comment: https://github.com/GoogleCloudPlatform/google-auth-library-python/issues/169#issuecomment-315417916, I implemented my appengine_config.py file to be: 

    import os
    import google
    from google.appengine.ext import vendor
    
    lib_directory = os.path.dirname(__file__) + '/lib'
    
    # Change where to find the google package (point to the lib/ directory)
    google.__path__ = [os.path.join(lib_directory, 'google')] + google.__path__
    
    # Add any libraries install in the "lib" folder.
    vendor.add(lib_directory)

I'm now seeing the following error when deploying the dev_appserver.py:

    Traceback (most recent call last):
      File "/google/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 240, in Handle
        handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
      File "/google/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 299, in _LoadHandler
      1 import os                                                                                                                      
        handler, path, err = LoadObject(self._handler)
      File "/google/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 85, in LoadObject
        obj = __import__(path[0])
      File "/home/<server-name>/<project>/hello_world/main.py", line 20, in <module>
        from sheets import data
      File "/home/<server-name>/<project>/hello_world/sheets.py", line 19, in <module>
        data = service.spreadsheets().values().get(spreadsheetId=spreadsheetId, range=rangeName).execute() # files().list().execute()
      File "/home/<server-name>/<project>/hello_world/lib/oauth2client/_helpers.py", line 133, in positional_wrapper
        return wrapped(*args, **kwargs)
      File "/home/<server-name>/<project>/hello_world/lib/googleapiclient/http.py", line 844, in execute
        raise HttpError(resp, content, uri=self.uri)
    HttpError: <HttpError 403 when requesting https://sheets.googleapis.com/v4/spreadsheets/<spreadsheet-key>/values/A1%3AA5?alt=json returned "Google Sheets API has not been used in project cloud-devshell-dev before or it is disabled. Ena
    ble it by visiting https://console.developers.google.com/apis/api/sheets.googleapis.com/overview?project=cloud-devshell-dev then re
    try. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.">

Then on deployment:

          (/base/alloc/tmpfs/dynamic_runtimes/python27/a7637d5531ec9deb_unzipped/python27_lib/versions/1/google/appengine/runtime/wsgi.py:263)
    Traceback (most recent call last):
      File "/base/alloc/tmpfs/dynamic_runtimes/python27/a7637d5531ec9deb_unzipped/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 240, in Handle
        handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
      File "/base/alloc/tmpfs/dynamic_runtimes/python27/a7637d5531ec9deb_unzipped/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 299, in _LoadHandler
        handler, path, err = LoadObject(self._handler)
      File "/base/alloc/tmpfs/dynamic_runtimes/python27/a7637d5531ec9deb_unzipped/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 85, in LoadObject
        obj = __import__(path[0])
      File "/base/data/home/apps/p~<project>/20180310t085554.408207159076907912/main.py", line 20, in <module>
        from sheets import data
      File "/base/data/home/apps/p~<project>/20180310t085554.408207159076907912/sheets.py", line 1, in <module>
        from google.auth import app_engine
      File "/base/data/home/apps/p~<project>/20180310t085554.408207159076907912/lib/google/auth/app_engine.py", line 29, in <module>
        from google.auth import crypt
      File "/base/data/home/apps/p~<project>/20180310t085554.408207159076907912/lib/google/auth/crypt/__init__.py", line 39, in <module>
        from google.auth.crypt import rsa
      File "/base/data/home/apps/p~<project>/20180310t085554.408207159076907912/lib/google/auth/crypt/rsa.py", line 27, in <module>
        from google.auth.crypt import _python_rsa
      File "/base/data/home/apps/p~<project>/20180310t085554.408207159076907912/lib/google/auth/crypt/_python_rsa.py", line 24, in <module>
        from pyasn1.codec.der import decoder
    ImportError: No module named pyasn1.codec.der

The Sheets API is enabled in the project I'm running. However, it seems like Cloudshell needs Sheets API permissions. 

How would I use this tutorial: https://developers.google.com/api-client-library/python/auth/service-accounts on App Engine and Cloudshell to view Sheets in development and deployment? I'm also fine knowing this isn't possible and I can only deploy the app to view the cells from a Sheets file.

**Comment by duggelz** [comment]
@iethan This is, unfortunately, the wrong bug tracker for your questions.  Can you please open a new issue on the official App Engine issue tracker:

https://issuetracker.google.com/issues/new?component=187191&template=0

You can see existing open issues here:

https://issuetracker.google.com/savedsearches/559750
