### ISSUE TITLE
AUTH_DOMAIN not being set

### ISSUE THREAD

**Issue by dmytton** [GoogleCloudPlatform/appengine-python-vm-runtime#35]
The environment variable https://github.com/GoogleCloudPlatform/appengine-python-vm-runtime/blob/master/python_vm_runtime/google/appengine/api/users.py#L116 is not being set on a Google Apps App Engine project. This is causing authentication to fail:

```
Traceback (most recent call last):\n
File \"/home/vmagent/python_vm_runtime/google/appengine/ext/vmruntime/middlewares.py\", line 283, in ErrorLoggingWrapper
\n
return app(wsgi_env, start_response)\n
File \"/home/vmagent/python_vm_runtime/google/appengine/ext/vmruntime/middlewares.py\", line 271, in LogRequestWrapper\n
return app(wsgi_env, StartResponseWrapper)\n
File \"/home
/vmagent/python_vm_runtime/google/appengine/ext/vmruntime/meta_app.py\", line 454, in __call__\n
return self.GetUserAppAndServe(script, env, start_response)\n
File \"/home/vmagent/python_vm_runtime/google/appengine/ext/vmrun
time/meta_app.py\", line 549, in GetUserAppAndServe\n
app, mod_file = self.GetUserApp(script)\n
File \"/home/vmagent/python_vm_runtime/google/appengine/ext/vmruntime/meta_app.py\", line 410, in GetUserApp\n
app = _AppFrom27StyleScript(script)\n
File \"/home/vmagent/python_vm_runtime/google/appengine/ext/vmruntime/meta_app.py\", line 270, in _AppFrom27StyleScript\n
app, filename, err = wsgi.LoadObject(script)\n
File \"/home/vmagent/python_vm_runtime/google/appengine/runtime/wsgi.py\", line 85, in LoadObject\n
obj = __import__(path[0])\n
File \"/home/vmagent/app/search.py\", line 14, in <module>\n
from users import *\n File \"/home/vmagent/app/users.py\", line 12, in <module>\n
user = users.get_current_user()\n
File \"/home/vmagent/python_vm_runtime/google/appengine/api/users.py\", line 301, in get_current_user\n
return User()\n
File \"/home/vmagent/python_vm_runtime/google/appengine/api/users.py\", line 117, in __init__\n
assert _auth_domain\nAssertionError\n
```

This is noted in https://github.com/GoogleCloudPlatform/appengine-python-vm-runtime#caveats that the login handler is not supported but the handler is being invoked and an error is being thrown.

I was able to solve this by changing https://github.com/GoogleCloudPlatform/appengine-python-vm-runtime/blob/master/python_vm_runtime/google/appengine/api/users.py#L116 to hard code my Apps domain as the `AUTH_DOMAIN`. I was then able to bundle this as a custom runtime as part of the Managed VM. It just seems like a bug in the runtime, not correctly setting the `AUTH_DOMAIN`.

See also Google Enterprise support case 07656056 where I reported this on 14th October but with no fix so far.

**Comment by andrewsg** [comment]
This is a reserved environment variable, set by reserved_env_keys_for_wsgi_env in middleware.py. This functionality appears to be working properly in my tests. If it's not working for you, that probably means that the request header is not properly being set upstream. Can you check and see if the request header HTTP_X_APPENGINE_AUTH_DOMAIN is being set to a non-null value?

If you are running your code outside of the normal request/response path somehow, that may explain this error.

**Comment by dmytton** [comment]
I reverted to the standard MVM runtime and it's working as expected now, so looks like this was fixed at some point.
