### ISSUE TITLE
Repeated nested properties of StructuredProperty

### ISSUE THREAD

**Issue by brianmhunt** [GoogleCloudPlatform/appengine-python-vm-runtime#40]
I'm just copying the gist of a [SO question](http://stackoverflow.com/q/34790724/19212). In particular, the docs for AppEngine state:

> Although a StructuredProperty can be repeated and a StructuredProperty can contain another StructuredProperty, beware: **if one structured property contains another, only one of them can be repeated.**

This implies that nested structured properties cannot both be repeated.  However, the [condition in the code](https://github.com/GoogleCloudPlatform/appengine-python-vm-runtime/blob/master/python_vm_runtime/google/appengine/ext/ndb/model.py#L2238) appears to be that *any* repeated property cannot be contained in a repeated StructuredProperty, as doing so will throw something like:

> TypeError: This StructuredProperty cannot use repeated=True because its model class (KeyList) contains repeated properties (directly or indirectly).

It may be that the documentation I've quoted at the top are just unclear or I've misread them.

However, if a repeated StructuredProperty ought to be able to contain repeated properties (that are not of the StructuredProperty variety), then the solution might be to change the condition from `if modelclass._has_repeated` to (something like):

```python
    if modelclass._has_repeated and isinstance(modelclass, StructuredProperty):
```

Cheers

**Comment by brianmhunt** [comment]
While it does not appear determinative, I also just noted [the documentation in the code](https://github.com/GoogleCloudPlatform/appengine-python-vm-runtime/blob/master/python_vm_runtime/google/appengine/ext/ndb/model.py#L181-L184):

> Structured property types can be nested arbitrarily deep, but in a
hierarchy of nested structured property types, only one level can have
the repeated flag set.  It is fine to have multiple structured
properties referencing the same model class.

It's not clear if the restriction is intended to be one level of structured property, or the leaf properties can also be repeated.

**Comment by jonparrott** [comment]
@bryanmau1 can you take a look at this? If it's a documentation issue, feel free to file a bug against the docs.

**Comment by pcostell** [comment]
@jonparrot -- Yup this is a docs issue. Only one layer of repeated properties is allowed in ndb. So a StructuredProperty can be repeated but then none of the properties in that StructuredProperty can be repeated.

**Comment by bryanmau1** [comment]
Thanks for the reply, for future reference, the proper place to bring up issues about NDB is this GitHub.

https://github.com/GoogleCloudPlatform/datastore-ndb-python

**Comment by brianmhunt** [comment]
Thanks @bryanmau1  & @pcostell
