### ISSUE TITLE
Contributing to python vm?

### ISSUE THREAD

**Issue by mikelambert** [GoogleCloudPlatform/appengine-python-vm-runtime#48]
Hey sorry to ask a question via issues, but if we submit any patches to python_vm_runtime, would that make it upstream to GAE core? Or is this strictly a downstream fork that gets pushed to the VM runtimes?

The last push to https://code.google.com/p/googleappengine/source/list is 1.9.30 in November, and I don't know where I should be trying to contribute patches to. (Why oh why hasn't this moved to github like everything else? :( )

And as a python vm runtime user...thanks! I've used this code dump a few times already to help debug issues, much appreciated!

**Comment by jonparrott** [comment]
I'm going to flesh this out when I fix #43.

> would that make it upstream to GAE core? Or is this strictly a downstream fork that gets pushed to the VM runtimes?

I believe everything in `python_vm_runtime` folder is exported code and won't be upstreamed. Everything else is fair game. @andrewsg to confirm.

> I don't know where I should be trying to contribute patches to. (Why oh why hasn't this moved to github like everything else? :( )

We're working on moving the Google App Engine SDK to github, but it's not an easy process with a project that large. For now, the best way to submit patches is as describe on the Google Code homepage - file a bug with the diff attached.

**Comment by andrewsg** [comment]
That's correct, `python_vm_runtime` is essentially used as a vendored API library and is downstream of the source. I want to eventually extract just the components of the package that we need, discard the rest, re-add the stripped comments and make it a first-class component of this runtime, but that would be a major fork.

**Comment by mikelambert** [comment]
Thanks for answering m question.

But @andrewsg , just so you're aware: This project is the *only* place on the internet I can find the python_vm_runtime code that is used when I run on a Managed VM. I have found it useful when debugging code, or attempting to do other changes or monkey patches.

So if you ever do that "major fork" to only include a subset, I'd prefer some other repo to have a copy of the source that I rnu on my Managed VMs (so I am not forced to try to download it off the VM machine...)  Thanks!
